name: Holly Heisey Design
favicon: null
layout_spectrum: 0.29329391149803996
typography_spectrum: 0.742655705427751
title: Holly Heisey Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#717171'
    - '#d73f20'
    - '#68eeff'
  brandStrength: 0.4375
  lightness: 0.521302325418219
  saturation: 0.18550178757868707
  rhythmicContrast: 0.45839475071989
purpose: []
