typography_spectrum: null
color:
  brandColors: []
  brandStrength: null
  lightness: null
  saturation: null
  rhythmicContrast: null
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Holly Heisey
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Holly Heisey
description: Science fiction and fantasy author.
purpose: []
